# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ubde8J6G-bFvGI_dqCDvmzrTl6EOLi0i
"""

import pandas as pd
baza={
  "FISH":[  "Turg'unov Abdulbosit "  ,"Abduhalimov Husniddin","Raxmatov Husniddin",'Komilova Dinora' , 'Sodiqova Mahliyo','Tursunov Muhammadqodir','Eshboyev Ilhom','Yusupov Temur','Sulaymonova Mahliyo' ,'Mamatvaliyev Dilshodbek'],
  "Yoshi":['18', '19','19' ,'19','19','19' ,'19','20','19' ,'19' ],
  "Maktabi":[  '12-maktab' ,'20-maktab','33-maktab','5-maktab','5-maktab','24-maktab','21-maktab','25-maktab','21-maktab' ,'7-maktab'    ],
  "Jinsi":[ 'erkak' ,'erkak','erkak' ,'ayol'  ,'ayol','erkak',"erkak" ,'erkak'  ,'ayol' ,'erkak' ],
  "Manzili":[   'Shahrixon tumani','Andijon shahar','Beshariq tumani','Beshariq tumani',"Beshariq tumani",'Shahrixon tumani','Samarqand viloyati','Xorazm viloyati',"Farg'ona shahar",'Namangan viloyati'    ]

 }
db=pd.DataFrame(baza)
print(db)

filter=db[db['Jinsi']=="erkak"]
print(filter)

filter=db[db['Jinsi']=="ayol"]
print(filter)

filter=db[db['Yoshi']=="20"]
print(filter)

filter=db[db['Manzili']=="Shahrixon tumani"]
print(filter)

filter=db[db['Maktabi']=="21-maktab"]
print(filter)

filter=db[db['Manzili']=="Farg'ona shahar"]
print(filter)

filter=db[(db['Jinsi']=="erkak") & (db['Manzili']=="Namangan viloyati" )]
print(filter)

filter=db[(db['Jinsi']=="erkak") & (db['Manzili']=="Shahrixon tumani" ) & (db["Yoshi"]=='19' )]
print(filter)